/** Public, reviewed marketing copy. Each entry is Simplified / Traditional / English. */
const entries = {
  "shell.products": ["产品与方案", "產品與方案", "Solutions"],
  "shell.academy": ["AI 实战培训", "AI 實戰培訓", "AI Academy"],
  "shell.practice": ["案例与实践", "案例與實踐", "Our work"],
  "shell.about": ["关于兰芯", "關於蘭芯", "About us"],
  "shell.contact": ["聊聊你的业务", "聊聊你的業務", "Let’s talk"],
  "shell.theme": ["外观模式", "外觀模式", "Appearance"],
  "shell.system": ["跟随系统", "跟隨系統", "System"],
  "shell.light": ["白天", "白天", "Light"],
  "shell.dark": ["黑夜", "黑夜", "Dark"],
  "shell.navigation": ["网站主导航", "網站主導覽", "Main navigation"],
  "shell.footerNavigation": ["页脚导航", "頁尾導覽", "Footer navigation"],
  "nav.products": ["产品与方案", "產品與方案", "Solutions"],
  "nav.academy": ["AI 实战培训", "AI 實戰培訓", "AI Academy"],
  "nav.practice": ["案例与实践", "案例與實踐", "Our work"],
  "nav.method": ["关于兰芯", "關於蘭芯", "About us"],
  "nav.open": ["资源与开源", "資源與開源", "Open resources"],
  "nav.cta": ["聊聊你的业务", "聊聊你的業務", "Let’s talk"],
  "new.skip": ["跳到主要内容", "跳到主要內容", "Skip to content"],
  "new.eyebrow": ["AI 产品 · 业务落地 · 实战培训", "AI 產品 · 業務落地 · 實戰培訓", "AI PRODUCTS · REAL BUSINESS · HANDS-ON LEARNING"],
  "new.hero1": ["让 AI 看懂业务", "讓 AI 看懂業務", "AI that understands."],
  "new.hero2": ["让经营先行一步", "讓經營先行一步", "Business that moves."],
  "new.intro": ["从汽车零售与售后出发，把 AI 做成真正用得上的产品，也让更多团队拥有把想法落地的能力。", "從汽車零售與售後出發，把 AI 做成真正用得上的產品，也讓更多團隊擁有把想法落地的能力。", "Rooted in automotive retail and aftersales. We build AI products for real work — and help teams turn their own ideas into working tools."],
  "new.explore": ["探索产品与方案", "探索產品與方案", "Explore our solutions"],
  "new.academyLink": ["了解 AI 实战培训", "了解 AI 實戰培訓", "Discover AI Academy"],
  "new.heroNote": ["以真实业务为起点，以可用成果为答案。", "以真實業務為起點，以可用成果為答案。", "Built around real problems. Measured by useful work."],
  "new.scroll": ["向下探索", "向下探索", "SCROLL TO EXPLORE"],
  "new.motionStory": ["从一个信号，到业务的下一步", "從一個信號，到業務的下一步", "From a signal to the next step"],
  "new.motionStep1": ["看见信号", "看見信號", "Discover"],
  "new.motionStep2": ["建立连接", "建立連接", "Connect"],
  "new.motionStep3": ["推动行动", "推動行動", "Act"],
  "new.motionLabel": ["首屏动效阶段", "首屏動效階段", "Visual story stages"],
  "new.motionPause": ["暂停", "暫停", "Pause"],
  "new.motionPlay": ["继续", "繼續", "Play"],
  "new.motionReplay": ["重看", "重看", "Replay"],
  "new.motionPauseAll": ["暂停动效", "暫停動效", "Pause motion"],
  "new.motionPlayAll": ["开启动效", "開啟動效", "Play motion"],
  "new.strip1": ["发现新机会", "發現新機會", "Discover opportunities"],
  "new.strip2": ["连接客户关系", "連接客戶關係", "Connect customer journeys"],
  "new.strip3": ["协同门店运营", "協同門店營運", "Coordinate operations"],
  "new.strip4": ["培养 AI 能力", "培養 AI 能力", "Build AI capability"],
  "new.productsLabel": ["产品与解决方案", "產品與解決方案", "PRODUCTS & SOLUTIONS"],
  "new.productsTitle": ["把业务里的下一步，\n变得更清楚。", "把業務裡的下一步，\n變得更清楚。", "Make the next step\nclearer."],
  "new.productsIntro": ["从公域需求到客户关系，再到车间协同。围绕具体岗位，解决具体问题。", "從公域需求到客戶關係，再到車間協同。圍繞具體崗位，解決具體問題。", "From public demand to customer relationships and workshop coordination. Specific tools for specific jobs."],
  "new.allSolutions": ["查看全部方案", "查看全部方案", "All solutions"],
  "new.lhCategory": ["公域获客 · LeadsHunter", "公域獲客 · LeadsHunter", "LEAD INTELLIGENCE · LEADSHUNTER"],
  "new.lhTitle": ["客户的下一句话，\n可能就是你的新机会。", "客戶的下一句話，\n可能就是你的新機會。", "Their next question.\nYour next opportunity."],
  "new.lhDescription": ["从抖音、小红书的公开讨论中发现购车需求，理解意向和上下文，把可跟进的线索送到销售手上。", "從抖音、小紅書的公開討論中發現購車需求，理解意向和上下文，把可跟進的線索送到銷售手上。", "Find buying intent in public conversations on Douyin and Xiaohongshu. Understand the context and deliver actionable leads to your sales team."],
  "new.lhStatus": ["国内产品已投入运行", "國內產品已投入運行", "Operating in mainland China"],
  "new.lhFeature1": ["公开需求发现", "公開需求發現", "Public demand discovery"],
  "new.lhFeature2": ["意向识别与摘要", "意向識別與摘要", "Intent & context"],
  "new.lhFeature3": ["组织分发与销售 App", "組織分發與銷售 App", "Team routing & sales app"],
  "new.lhLink": ["了解线索猎手", "了解線索獵手", "Explore LeadsHunter"],
  "new.preview": ["产品演示画面", "產品示範畫面", "Illustrative product visual"],
  "new.vectCategory": ["客户关系 · VECT", "客戶關係 · VECT", "CUSTOMER RELATIONSHIPS · VECT"],
  "new.vectTitle": ["让每一次服务，\n都有下一次连接。", "讓每一次服務，\n都有下一次連接。", "Every service.\nA lasting connection."],
  "new.vectDescription": ["连接预约、回访与服务记录，识别需要关注的客户关系，让跟进有依据、有人负责。", "連接預約、回訪與服務記錄，識別需要關注的客戶關係，讓跟進有依據、有人負責。", "Connect appointments, follow-ups and service records. Identify relationships that need attention and give each action an owner."],
  "new.vectStatus": ["飞书方案验证 · SaaS 筹备中", "飛書方案驗證 · SaaS 籌備中", "Feishu workflow validated · SaaS in preparation"],
  "new.tactCategory": ["车间协同 · TACT", "車間協同 · TACT", "WORKSHOP COORDINATION · TACT"],
  "new.tactTitle": ["每台车的进度，\n每个人都心中有数。", "每台車的進度，\n每個人都心中有數。", "Every vehicle.\nOne shared picture."],
  "new.tactDescription": ["把工单状态、工序责任与等待风险连起来，让服务顾问、技师与管理者协同推进交付。", "把工單狀態、工序責任與等待風險連起來，讓服務顧問、技師與管理者協同推進交付。", "Connect work-order status, responsibilities and waiting risks so service advisors, technicians and managers can coordinate delivery."],
  "new.tactStatus": ["飞书方案验证 · SaaS 前期建设", "飛書方案驗證 · SaaS 前期建設", "Feishu workflow validated · SaaS in preparation"],
  "new.viewSolution": ["了解方案", "了解方案", "View solution"],
  "new.globalTitle": ["把业务视野，延伸到更远。", "把業務視野，延伸到更遠。", "See opportunities further afield."],
  "new.globalDescription": ["LeadsHunter Global 探索 Facebook、TikTok 的海外汽车需求发现与意向分析。目前提供受控试点，销售端交付仍在完善。", "LeadsHunter Global 探索 Facebook、TikTok 的海外汽車需求發現與意向分析。目前提供受控試點，銷售端交付仍在完善。", "LeadsHunter Global explores automotive demand on Facebook and TikTok. Controlled pilots are available; the sales delivery experience is still being developed."],
  "new.globalLink": ["交流海外试点", "交流海外試點", "Discuss a global pilot"],
  "new.academyLabel": ["兰芯 AI 实战培训", "蘭芯 AI 實戰培訓", "LAN CLOUD AI ACADEMY"],
  "new.academyTitle": ["好工具之外，\n还需要会用它的人。", "好工具之外，\n還需要會用它的人。", "Good tools need\npeople who can use them."],
  "new.academyDescription": ["从完成第一份经营简报，到做出自己的 AI 工具。用真实任务学习，把能力带回工作现场。", "從完成第一份經營簡報，到做出自己的 AI 工具。用真實任務學習，把能力帶回工作現場。", "From a first business brief to your own AI tool. Learn through real tasks, then take the capability back to work."],
  "new.course1Title": ["兰芯 AI 实战课", "蘭芯 AI 實戰課", "Practical AI classes"],
  "new.course1Description": ["从经营简报与小工具入手，迈出 AI 应用第一步。", "從經營簡報與小工具入手，邁出 AI 應用第一步。", "Start with business briefs and small tools for everyday work."],
  "new.course1Tag": ["业务人员 · 入门实践", "業務人員 · 入門實踐", "BUSINESS TEAMS · GET STARTED"],
  "new.course2Title": ["企业 MVP 三天定制课", "企業 MVP 三天定製課", "3-day enterprise workshop"],
  "new.course2Description": ["围绕一个真实业务问题，完成可验收的 AI 工具原型。", "圍繞一個真實業務問題，完成可驗收的 AI 工具原型。", "Turn one real business problem into a verifiable AI prototype."],
  "new.course2Tag": ["企业团队 · 3 天实战", "企業團隊 · 3 天實戰", "ENTERPRISE TEAMS · 3 DAYS"],
  "new.course3Title": ["系统 FDE 培养", "系統 FDE 培養", "FDE development programme"],
  "new.course3Description": ["21 课、84 课时，系统建立从业务发现到应用交付的能力。", "21 課、84 課時，系統建立從業務發現到應用交付的能力。", "21 lessons and 84 hours, from business discovery to application delivery."],
  "new.course3Tag": ["内部 AI 人才 · 系统进阶", "內部 AI 人才 · 系統進階", "INTERNAL AI TALENT · GO DEEPER"],
  "new.practiceLabel": ["案例与实践", "案例與實踐", "SELECTED WORK"],
  "new.practiceTitle": ["让想法走出文档，\n进入日常。", "讓想法走出文件，\n進入日常。", "From an idea on paper\nto everyday work."],
  "new.practiceIntro": ["从线索跟进到团队协作，在真实流程中打磨工具，在开放实践中积累方法。", "從線索跟進到團隊協作，在真實流程中打磨工具，在開放實踐中積累方法。", "From lead follow-up to team workflows. We refine tools through real processes and share what we learn."],
  "new.practiceLink": ["浏览我们的实践", "瀏覽我們的實踐", "Explore our work"],
  "new.ledgerTitle": ["云朵记账", "雲朵記賬", "Cloud Ledger"],
  "new.ledgerDescription": ["把订阅、账期与报销整理到同一条可追溯的工作流。", "把訂閱、賬期與報銷整理到同一條可追溯的工作流。", "Subscriptions, billing cycles and reimbursements in one traceable workflow."],
  "new.ledgerTag": ["企业工具 · 开源实践", "企業工具 · 開源實踐", "BUSINESS TOOL · OPEN SOURCE"],
  "new.commerceTitle": ["商城与会员增长", "商城與會員增長", "Commerce & member growth"],
  "new.commerceDescription": ["围绕购物、邀请、优惠与订单履约，连接从参与到成交的业务流程。", "圍繞購物、邀請、優惠與訂單履約，連接從參與到成交的業務流程。", "Connect shopping, referrals, offers and order fulfilment into a coherent customer journey."],
  "new.commerceTag": ["业务系统 · 项目实践", "業務系統 · 專案實踐", "BUSINESS SYSTEM · PROJECT WORK"],
  "new.artistTitle": ["艺匠市集", "藝匠市集", "Artist Marketplace"],
  "new.artistDescription": ["为独立创作者探索定制商品、订单与履约的完整应用。", "為獨立創作者探索定製商品、訂單與履約的完整應用。", "An application example connecting custom products, orders and fulfilment for independent creators."],
  "new.artistTag": ["定制商城 · 演示项目", "定製商城 · 示範專案", "CUSTOM COMMERCE · DEMO PROJECT"],
  "new.methodLabel": ["关于兰芯", "關於蘭芯", "THE WAY WE WORK"],
  "new.methodTitle": ["先走进业务，\n再把 AI 带进去。", "先走進業務，\n再把 AI 帶進去。", "Understand the work.\nThen bring in AI."],
  "new.methodIntro": ["我们相信，有用的 AI 来自对业务的理解。把规则、流程与人的经验连接起来，让每一步改变都能落到具体工作中。", "我們相信，有用的 AI 來自對業務的理解。把規則、流程與人的經驗連接起來，讓每一步改變都能落到具體工作中。", "Useful AI starts with understanding a business. We connect its rules, processes and human experience so each improvement has a place in daily work."],
  "new.step1Title": ["找到值得解决的问题", "找到值得解決的問題", "Find the right problem"],
  "new.step1Description": ["走进岗位和流程，明确目标、约束与判断依据。", "走進崗位和流程，明確目標、約束與判斷依據。", "Understand the roles, goals, constraints and evidence."],
  "new.step2Title": ["先在小范围里跑通", "先在小範圍裡跑通", "Prove it on a small scale"],
  "new.step2Description": ["用原型与真实任务验证，把问题尽早暴露出来。", "用原型與真實任務驗證，把問題儘早暴露出來。", "Use prototypes and real tasks to uncover problems early."],
  "new.step3Title": ["让团队真正用起来", "讓團隊真正用起來", "Make it work for the team"],
  "new.step3Description": ["交付工具，也交付方法，在使用与反馈中持续改进。", "交付工具，也交付方法，在使用與回饋中持續改進。", "Deliver the tool and the know-how. Improve through use and feedback."],
  "new.openTitle": ["把经验开放，让实践继续。", "把經驗開放，讓實踐繼續。", "Shared knowledge. Continuing practice."],
  "new.openIntro": ["公开课程、开源工具与训练评估材料，欢迎阅读、使用和交流。", "公開課程、開源工具與訓練評估材料，歡迎閱讀、使用和交流。", "Explore public curricula, open tools and evaluation resources."],
  "new.trainingGround": ["线索模型训练场", "線索模型訓練場", "Lead evaluation training ground"],
  "new.contactTitle": ["从一个业务问题，\n开始一次有用的改变。", "從一個業務問題，\n開始一次有用的改變。", "A real challenge.\nA useful next step."],
  "new.contactIntro": ["聊聊你的场景与目标，一起找到可落地的下一步。", "聊聊你的場景與目標，一起找到可落地的下一步。", "Tell us about your work and goals. Let’s find a practical way forward."],
  "new.inquiryProduct": ["产品与方案", "產品與方案", "Products & solutions"],
  "new.inquiryTraining": ["企业 AI 培训", "企業 AI 培訓", "AI training"],
  "new.inquiryGlobal": ["海外业务试点", "海外業務試點", "Global pilot"],
  "new.inquiryProject": ["业务系统合作", "業務系統合作", "Custom project"],
  "new.inquiryLabel": ["选择交流方向", "選擇交流方向", "Choose a topic"],
  "new.inquiryHint": ["我们可以一起梳理适用场景、交付范围与演示安排。", "我們可以一起梳理適用場景、交付範圍與示範安排。", "We can discuss the right use case, delivery scope and a demo."],
  "new.inquiryTrainingHint": ["告诉我们团队的岗位与学习目标，一起选择合适的培训路径。", "告訴我們團隊的崗位與學習目標，一起選擇合適的培訓路徑。", "Tell us about your team and learning goals to find the right programme."],
  "new.inquiryGlobalHint": ["交流目标市场与平台范围，确认当前试点能力和合作方式。", "交流目標市場與平台範圍，確認當前試點能力和合作方式。", "Discuss your target market, platforms and the scope of the current pilot."],
  "new.inquiryProjectHint": ["从现有工作流程与具体问题出发，讨论系统实施的可能性。", "從現有工作流程與具體問題出發，討論系統實施的可能性。", "Start with your current workflow and discuss what a useful system could do."],
  "new.email": ["通过邮件聊聊", "透過郵件聊聊", "Start an email"],
  "new.wecom": ["添加企业微信", "新增企業微信", "Connect on WeCom"],
  "new.download": ["客户端下载", "客戶端下載", "App downloads"],
  "new.footerLine": ["把 AI 的可能，变成业务的日常。", "把 AI 的可能，變成業務的日常。", "Make AI part of everyday business."],
  "new.top": ["返回顶部", "返回頂部", "Back to top"],
  "new.solutionsHero": ["从业务问题出发，\n找到合适的解法。", "從業務問題出發，\n找到合適的解法。", "Start with your business.\nFind the right solution."],
  "new.solutionsIntro": ["围绕汽车零售与售后的关键岗位，连接需求发现、客户服务与车间协作。每一项方案都明确当前的交付形态。", "圍繞汽車零售與售後的關鍵崗位，連接需求發現、客戶服務與車間協作。每一項方案都明確當前的交付形態。", "Connect demand discovery, customer service and workshop coordination. Every solution is clear about its current delivery stage."],
  "new.forWho": ["适用团队", "適用團隊", "WHO IT IS FOR"],
  "new.lhAudience": ["经销商集团、直营门店、销售与 DCC 团队", "經銷商集團、直營門店、銷售與 DCC 團隊", "Dealer groups, retail stores, sales and customer development teams"],
  "new.vectAudience": ["服务顾问、客户服务团队、店长与区域管理者", "服務顧問、客戶服務團隊、店長與區域管理者", "Service advisors, customer service teams, store and regional managers"],
  "new.tactAudience": ["车间主管、技师、服务顾问与门店管理者", "車間主管、技師、服務顧問與門店管理者", "Workshop leads, technicians, service advisors and store managers"],
  "new.delivery": ["当前交付形态", "當前交付形態", "CURRENT DELIVERY"],
  "new.lhDelivery": ["国内运营后台与销售 App；iPhone 经 TestFlight，Android 经客户端下载渠道。具体开通范围请联系确认。", "國內營運後台與銷售 App；iPhone 經 TestFlight，Android 經客戶端下載管道。具體開通範圍請聯繫確認。", "Mainland operations console and sales app. iPhone distribution uses TestFlight; Android uses the download channel. Contact us to confirm access."],
  "new.vectDelivery": ["已有飞书业务方案验证，自有 SaaS 正在筹备。可交流客户档案、服务记录与跟进流程。", "已有飛書業務方案驗證，自有 SaaS 正在籌備。可交流客戶檔案、服務記錄與跟進流程。", "The Feishu workflow has been validated; a standalone SaaS is in preparation. Discuss customer profiles, service history and follow-up processes."],
  "new.tactDelivery": ["已有飞书业务方案验证，自有 SaaS 处于前期建设。可交流工序协同、状态追踪与责任分工。", "已有飛書業務方案驗證，自有 SaaS 處於前期建設。可交流工序協同、狀態追蹤與責任分工。", "The Feishu workflow has been validated; a standalone SaaS is in preparation. Discuss coordination, status tracking and responsibilities."],
  "new.solutionContact": ["交流这个方案", "交流這個方案", "Discuss this solution"],
  "new.practiceHero": ["在具体的事情里，\n看见 AI 的价值。", "在具體的事情裡，\n看見 AI 的價值。", "Real tasks.\nUseful possibilities."],
  "new.practiceDetail": ["从汽车零售到团队协作，看看一个业务问题如何变成清晰的流程，再落到具体的工具与行动中。", "從汽車零售到團隊協作，看看一個業務問題如何變成清晰的流程，再落到具體的工具與行動中。", "From automotive retail to team operations, explore how a business problem becomes a clear workflow, a useful tool and a practical next step."],
  "new.workflow": ["工作如何发生", "工作如何發生", "HOW THE WORK FLOWS"],
  "new.lhWorkflow": ["发现公开讨论 → 分析意向与语境 → 分配给销售 → 回到原平台跟进", "發現公開討論 → 分析意向與語境 → 分配給銷售 → 回到原平台跟進", "Public conversation → intent and context → sales assignment → follow-up on the original platform"],
  "new.ledgerWorkflow": ["记录订阅 → 整理付款与账期 → 汇总报销候选 → 审批与留痕", "記錄訂閱 → 整理付款與賬期 → 彙總報銷候選 → 審批與留痕", "Record subscriptions → organise payers and cycles → group expenses → review and retain the trail"],
  "new.commerceWorkflow": ["活动参与 → 邀请与优惠 → 订单履约 → 奖励与退款处理", "活動參與 → 邀請與優惠 → 訂單履約 → 獎勵與退款處理", "Campaign participation → referrals and offers → fulfilment → rewards and refunds"],
  "new.artistWorkflow": ["展示作品 → 选择定制 → 创建订单 → 跟踪履约", "展示作品 → 選擇定製 → 建立訂單 → 追蹤履約", "Showcase work → customise → place an order → track fulfilment"],
  "new.viewProject": ["查看项目", "查看專案", "Explore project"],
  "new.discussProject": ["交流项目合作", "交流專案合作", "Discuss a project"],
  "new.lhPracticeTag": ["汽车零售 · 产品实践", "汽車零售 · 產品實踐", "AUTOMOTIVE RETAIL · PRODUCT WORKFLOW"],
  "new.lhPracticeTitle": ["线索发现与销售协作", "線索發現與銷售協作", "Lead discovery & sales workflows"],
};

export const getRedesignCopy = (locale = "zh-Hans") => {
  const index = locale === "en" ? 2 : locale === "zh-Hant" ? 1 : 0;
  return Object.fromEntries(Object.entries(entries).map(([key, values]) => [key, values[index]]));
};

export const REDESIGN_COPY_KEYS = Object.keys(entries);
