/** One static navigation and footer for every public company route. */
import { getI18nTable } from '../i18n.js';

export const SHELL_ROUTES = [
  { id: 'solutions', path: 'solutions/', key: 'shell.products' },
  { id: 'academy', path: 'ai-course/', key: 'shell.academy' },
  { id: 'practice', path: 'practice/', key: 'shell.practice' },
  { id: 'about', path: '#method', key: 'shell.about' },
];
const copy = getI18nTable('zh-Hans');
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const text = key => `<span data-i18n="${key}">${escape(copy[key] || key)}</span>`;
const arrow = '<span aria-hidden="true">↗</span>';
const brand = prefix => `<a class="lan-brand" href="${prefix}" aria-label="${escape(copy['nav.brand'])}" data-i18n-aria="nav.brand"><img src="https://img.lancloudtech.com/lanxin/webpage/images/logo/WEB-logo.svg" width="36" height="35" alt="" />${text('nav.brand')}</a>`;
const languages = () => `<div class="lan-languages" role="group" aria-label="${copy['lang.label']}" data-i18n-aria="lang.label">${[['zh-Hans','简','简体中文'],['zh-Hant','繁','繁體中文'],['en','EN','English']].map(([locale,label,name]) => `<button type="button" class="lan-language" data-shell-locale="${locale}" aria-label="${name}" aria-pressed="${locale === 'zh-Hans'}">${label}</button>`).join('')}</div>`;
export const themeControls = () => `<div class="lan-theme" role="group" aria-label="${copy['shell.theme']}" data-i18n-aria="shell.theme">${[['system','◐'],['light','☀'],['dark','☾']].map(([mode,icon]) => `<button type="button" data-theme-option="${mode}" aria-pressed="${mode === 'system'}"><span aria-hidden="true">${icon}</span>${text(`shell.${mode}`)}</button>`).join('')}</div>`;
const groupFor = route => route.startsWith('ai-course') ? 'academy' : route === 'internal-expense' ? 'solutions' : route;
export const shellHeader = (prefix = './', route = 'home', mainId = 'main') => `<a class="lan-skip" href="#${mainId}">${text('new.skip')}</a><header class="lan-header" data-site-header><div class="lan-header-inner">${brand(prefix)}<nav class="lan-primary" id="lan-primary" aria-label="${copy['shell.navigation']}" data-i18n-aria="shell.navigation">${SHELL_ROUTES.map(item => `<a href="${prefix}${item.path}" data-shell-route="${item.id}"${groupFor(route) === item.id ? ' aria-current="page"' : ''}>${text(item.key)}</a>`).join('')}<div class="lan-mobile-settings">${themeControls()}${languages()}</div></nav><div class="lan-header-actions"><a class="lan-contact" href="${prefix}${route.startsWith('ai-course') ? '?inquiry=training' : ''}#contact">${text('shell.contact')}${arrow}</a><button class="lan-menu-toggle" type="button" aria-controls="lan-primary" aria-expanded="false" aria-label="${copy['nav.menu']}" data-i18n-aria="nav.menu"><span></span><span></span></button></div></div></header>`;
export const shellFooter = (prefix = './') => `<footer class="lan-footer" data-site-footer><div class="lan-footer-main"><div class="lan-footer-brand">${brand(prefix)}<p>${text('new.footerLine')}</p></div><nav class="lan-footer-links" aria-label="${copy['shell.footerNavigation']}" data-i18n-aria="shell.footerNavigation">${SHELL_ROUTES.slice(0,3).map(item => `<a href="${prefix}${item.path}">${text(item.key)}</a>`).join('')}<a href="https://leadshunter.lancloudtech.com/">LeadsHunter ${arrow}</a><a href="${prefix}solutions/#vect">VECT</a><a href="${prefix}solutions/#tact">TACT</a><a href="${prefix}internal-expense/">${text('new.ledgerTitle')}</a><a href="https://appstore.lancloudtech.com/" data-umami-event="app_download">${text('new.download')}</a></nav><div class="lan-footer-contact"><a href="mailto:lance@lancloudtech.com">lance@lancloudtech.com</a><a href="tel:+86-17380566771">+86 173 8056 6771</a><div class="lan-footer-settings">${themeControls()}${languages()}</div></div></div><div class="lan-footer-legal"><div><p>${text('footer.company')}</p><p>${text('footer.tax')}</p><p>${text('footer.address')}</p></div><div class="lan-footer-registration"><a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">蜀ICP备2026002396号</a><a href="${prefix}sitemap/">${text('footer.sitemap')}</a><a href="https://github.com/LAN-Cloud-AI" target="_blank" rel="noopener">GitHub ${arrow}</a><p>© 2026 LAN Cloud AI</p></div></div></footer>`;
export const shellHead = prefix => `<script src="${prefix}site-theme.js"></script>\n<link rel="stylesheet" href="${prefix}site-shell.css" />\n<script type="module" src="${prefix}site-shell.js"></script>`;
